### ISSUE TITLE
integrate with sketch runner

### ISSUE THREAD

**Issue by ralts00** [Volorf/iShadow#1]
please integrate with sketch runner to install and find the fastest plugin :)

<img width="752" alt="captura de pantalla 2017-09-12 16 04 20" src="https://user-images.githubusercontent.com/5034252/30348153-0ca998c0-97d4-11e7-82fa-7c14630db1bb.png">

**Comment by Volorf** [comment]
@ralts00 Done :)
Thanks for the advice!
